name: payload-cms
region: nyc

# App service configuration
services:
  - name: payload-cms-app
    source_dir: /
    github:
      repo: sukottokun/payload-cms
      branch: main
      deploy_on_push: true
    build_command: corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm run build
    run_command: pnpm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /
    health_check:
      http_path: /
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
      - key: PORT
        value: "3000"
        scope: RUN_TIME
      - key: DATABASE_URI
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: PAYLOAD_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: NODE_OPTIONS
        value: "--no-deprecation --max-old-space-size=8000"
        scope: BUILD_TIME
      - key: NODE_OPTIONS
        value: "--no-deprecation"
        scope: RUN_TIME

# Database configuration (PostgreSQL)
# Uncomment and configure if you want Digital Ocean to create a managed database
# databases:
#   - name: payload-cms-db
#     engine: PG
#     version: "15"
#     production: true
#     db_name: payloadcms
#     db_user: payloadcms

